"""Metadata/*.config emitters: model_settings.config (XML), slice_info.config
(XML, header-only), project_settings.config (JSON, fixture-profile shape).

Deliberate omissions vs. real Bambu Studio output (documented as KNOWN GAPS
in tests/fixtures/README.md and asserted by the structural diff test):
  - no <assemble> section (assembly-feature positions; redundant with the
    <build><item> world transform this fixture already carries)
  - no source_file / source_object_id / source_volume_id / source_offset_*
    metadata (Bambu's part-history bookkeeping; not needed to prove parser
    structural handling)
  - no plater_name / locked / top_file / pick_file metadata (cosmetic UI
    fields; top_1.png / pick_1.png thumbnails are not generated)
"""
from __future__ import annotations

import json
from xml.sax.saxutils import escape


def build_model_settings_xml(objects: list[dict], plates: dict[str, list[dict]]) -> str:
    """`objects`: [{wrapper_id, mesh_id, name, extruder}]
    `plates`: {plate_id: [{object_id, instance_id, identify_id}]}"""
    object_blocks = []
    for obj in objects:
        name = escape(obj["name"])
        object_blocks.append(
            f'  <object id="{obj["wrapper_id"]}">\n'
            f'    <metadata key="name" value="{name}"/>\n'
            f'    <metadata key="extruder" value="{obj["extruder"]}"/>\n'
            f'    <part id="{obj["mesh_id"]}" subtype="normal_part">\n'
            f'      <metadata key="name" value="{name}"/>\n'
            '      <metadata key="matrix" value="1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1"/>\n'
            '      <mesh_stat edges_fixed="0" degenerate_facets="0" facets_removed="0" '
            'facets_reversed="0" backwards_edges="0"/>\n'
            "    </part>\n"
            "  </object>"
        )

    plate_blocks = []
    for plate_id, instances in plates.items():
        instance_lines = "\n    ".join(
            "<model_instance>\n"
            f'      <metadata key="object_id" value="{inst["object_id"]}"/>\n'
            f'      <metadata key="instance_id" value="{inst["instance_id"]}"/>\n'
            f'      <metadata key="identify_id" value="{inst["identify_id"]}"/>\n'
            "    </model_instance>"
            for inst in instances
        )
        plate_blocks.append(
            "  <plate>\n"
            f'    <metadata key="plater_id" value="{plate_id}"/>\n'
            f'    <metadata key="thumbnail_file" value="Metadata/plate_{plate_id}.png"/>\n'
            f"    {instance_lines}\n"
            "  </plate>"
        )

    return (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        "<config>\n"
        + "\n".join(object_blocks)
        + "\n"
        + "\n".join(plate_blocks)
        + "\n</config>"
    )


def build_slice_info_xml(client_version: str) -> str:
    """Header-only slice_info.config -- this fixture is never sliced, so no
    <plate> slice results are invented (would be fabricated data)."""
    return (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        "<config>\n"
        "  <header>\n"
        '    <header_item key="X-BBL-Client-Type" value="slicer"/>\n'
        f'    <header_item key="X-BBL-Client-Version" value="{client_version}"/>\n'
        "  </header>\n"
        "</config>"
    )


def build_project_settings_json(plate_count: int) -> str:
    """Minimal, honest, string-typed project profile ("A1 mini profile
    shape" per phase spec): small key set, scalars as strings, per-filament
    values as single-entry lists. Explicitly NOT a Bambu preset."""
    settings = {
        "_fixture_notice": "fixture profile, not a Bambu preset -- generated by this repo's own tooling",
        "printer_settings_id": "Fixture Generator A1 mini profile",
        "printer_model": "Bambu Lab A1 mini",
        "nozzle_diameter": ["0.4"],
        "bed_temperature": ["35"],
        "bed_temperature_initial_layer": ["35"],
        "nozzle_temperature": ["220"],
        "nozzle_temperature_initial_layer": ["220"],
        "layer_height": "0.2",
        "initial_layer_height": "0.2",
        "wall_loops": "2",
        "sparse_infill_density": "15%",
        "default_filament_profile": ["Generic PLA"],
        "plate_count": str(plate_count),
    }
    return json.dumps(settings, indent=1, sort_keys=True) + "\n"
